In [34]:
import pandas as pd
import numpy as np

In [35]:
filename = 'laptop_200.csv'
df = pd.read_csv(filename)
df.head()

,id,brand,series,weight,ram,price,graphics,disk,battery,display,processor,max_memory,url,image_url,rating
0,0,HP,14s-dy2506TU,1.46,8.0,38990,NaN,NaN,NaN,14.015748,3.7,16.0,https://amazon.in/gp/slredirect/picassoRedirec...,https://images-eu.ssl-images-amazon.com/images...,4.2 out of 5 stars
1,1,Lenovo,NaN,1.20,4.0,23890,NaN,NaN,8.0,11.600000,2.8,4.0,https://amazon.in/gp/slredirect/picassoRedirec...,https://m.media-amazon.com/images/I/41F52ef+pd...,3.8 out of 5 stars
2,2,ASUS,NaN,1.80,4.0,26990,4.0,256.0,6.0,17.795276,2.8,8.0,https://amazon.in/ASUS-15-6-inch-Integrated-Tr...,https://images-eu.ssl-images-amazon.com/images...,4.1 out of 5 stars
3,3,HP,NaN,3.00,NaN,19999,NaN,NaN,2.0,15.600000,2.2,16.0,https://amazon.in/Renewed-HP-650-Generation-Wa...,https://m.media-amazon.com/images/I/41+dy19aYE...,NaN
4,4,Lenovo,NaN,1.20,4.0,23890,NaN,NaN,8.0,11.600000,2.8,4.0,https://amazon.in/Lenovo-IdeaPad-Celeron-Plati...,https://m.media-amazon.com/images/I/41F52ef+pd...,3.8 out of 5 stars

In [36]:

def get_null_count(filename):
    df = pd.read_csv(filename)
    return df.isnull().sum()

In [37]:
get_null_count(filename)

id              0
brand           0
series        135
weight          0
ram             7
price           0
graphics      152
disk           63
battery       105
display        11
processor       8
max_memory     12
url             0
image_url       0
rating         15
dtype: int64

In [38]:
df.drop(columns= ["id"])

df['id'] = np.arange(len(df))

In [39]:
df.isnull().sum()

id              0
brand           0
series        135
weight          0
ram             7
price           0
graphics      152
disk           63
battery       105
display        11
processor       8
max_memory     12
url             0
image_url       0
rating         15
dtype: int64

In [40]:
def preprocess(df):
    df['weight'] = df['weight'].fillna(df['weight'].mean())
    df['ram'] = df['ram'].fillna(df['ram'].median())
    df['price'] = df['price'].fillna(df['price'].mean())
    df['graphics'] = df['graphics'].fillna(0)
    df['disk'] = df['disk'].fillna(df['disk'].median())
    df['battery'] = df['battery'].fillna(df['battery'].median())
    df['display'] = df['display'].fillna(df['display'].median())
    df['processor'] = df['processor'].fillna(df['processor'].median())
    df['max_memory'] = df['max_memory'].fillna(
        df['max_memory'].median())
    df['series'] = df['series'].fillna('')
    df['rating'] = df['rating'].fillna('3.0 out of 5 stars')
    return df

In [41]:
df = preprocess(df)

In [42]:
def normalise_min_max(df):
    '''
    df all cols should be numerical 
    note: normalising values between 1 to 2
    '''
    # df = pd.DataFrame()
    for column in df.columns:
        if df[column].dtype == float or  df[column].dtype == int  and column != 'id':
            df[column+"_norm"] = ((df[column] - df[column].min()) /
                                (df[column].max() - df[column].min())+1)
    return df

In [43]:
df = normalise_min_max(df)

df.head()

,id,brand,series,weight,ram,price,graphics,disk,battery,display,...,rating,weight_norm,ram_norm,price_norm,graphics_norm,disk_norm,battery_norm,display_norm,processor_norm,max_memory_norm
0,0,HP,14s-dy2506TU,1.46,8.0,38990,0.0,512.0,6.0,14.015748,...,4.2 out of 5 stars,1.186312,1.333333,1.128441,1.000,1.238095,1.36,1.389934,1.722222,1.200000
1,1,Lenovo,,1.20,4.0,23890,0.0,512.0,8.0,11.600000,...,3.8 out of 5 stars,1.087452,1.000000,1.044084,1.000,1.238095,1.52,1.000000,1.472222,1.000000
2,2,ASUS,,1.80,4.0,26990,4.0,256.0,6.0,17.795276,...,4.1 out of 5 stars,1.315589,1.000000,1.061402,1.125,1.111111,1.36,2.000000,1.472222,1.066667
3,3,HP,,3.00,8.0,19999,0.0,512.0,2.0,15.600000,...,3.0 out of 5 stars,1.771863,1.333333,1.022346,1.000,1.238095,1.04,1.645653,1.305556,1.200000
4,4,Lenovo,,1.20,4.0,23890,0.0,512.0,8.0,11.600000,...,3.8 out of 5 stars,1.087452,1.000000,1.044084,1.000,1.238095,1.52,1.000000,1.472222,1.000000

In [44]:
udf  = pd.read_csv('updated_dataset.csv')
udf.head()

,id,brand,series,weight,ram,price,graphics,disk,battery,display,...,ram_norm,price_norm,graphics_norm,disk_norm,battery_norm,display_norm,processor_norm,max_memory_norm,image_url,rating
0,0,ASUS,VivoBook 15 (2021),1.8,4,26990,4,256,6.0,17.795276,...,1.000000,1.072165,1.250,1.200000,1.2,2.000000,1.472222,1.142857,https://images-eu.ssl-images-amazon.com/images...,4.1 out of 5 stars
1,1,ASUS,ASUS VivoBook 15 X512DA,3.0,8,39490,0,512,8.0,15.600000,...,1.333333,1.201031,1.000,1.466667,1.4,1.645653,1.416667,1.142857,https://m.media-amazon.com/images/I/41Mdb2c+5g...,4.1 out of 5 stars
2,2,Lenovo,IdeaPad Slim 3,1.7,8,46790,2,512,8.0,15.600000,...,1.333333,1.276289,1.125,1.466667,1.4,1.645653,1.138889,1.285714,https://images-eu.ssl-images-amazon.com/images...,5.0 out of 5 stars
3,3,ASUS,VivoBook 14 (2021),1.6,8,29990,8,1024,6.0,15.984252,...,1.333333,1.103093,1.500,2.000000,1.2,1.707677,1.638889,1.285714,https://images-eu.ssl-images-amazon.com/images...,3.3 out of 5 stars
4,4,Lenovo,IdeaPad 1 11IGL05,1.2,4,24490,0,512,8.0,11.600000,...,1.000000,1.046392,1.000,1.466667,1.4,1.000000,1.472222,1.000000,https://m.media-amazon.com/images/I/41F52ef+pd...,4.0 out of 5 stars

In [50]:
def min_max_vals(df,column):
    return df[column].min(),df[column].max()

In [51]:
def dnorm(norm,min,max):
    return ((norm-1) * (max-min)+ min)

In [52]:
min,max = min_max_vals(udf,'weight')
norm = 1
dnorm(norm,min,max)

1.07

In [ ]:
[1.07,]
[1.75]